### ISSUE TITLE
Traffic Sources Report

### ISSUE THREAD

**Issue by currycoder** [gamernetwork/gastatsdash#13]
Traffic by source and movement period - period
Traffic by device i.e. Mobile, Desktop and Tablet and movement period - period
Social media traffic and movement period - period

**Comment by currycoder** [comment]
Related to #11 - possible alternative

**Comment by currycoder** [comment]
Need a new report class for this which marshalls data from google analytics using a new method on the  ```Analytics```  class.

This will also need a new template - https://docs.djangoproject.com/en/1.8/topics/templates/#the-django-template-language

**Comment by fayebutler** [comment]
- percentages and cumulative 
- charts??

**Comment by fayebutler** [comment]
devices : one chart for device category - create a plot to show overall trend?
one to show browser
