### ISSUE TITLE
One-off: network-wide report of traffic from social networks

### ISSUE THREAD

**Issue by MrJonty** [gamernetwork/gastatsdash#17]
For the AGM next week and on occasion in future - probably quarterly at most - we'd like to show the tangible traffic that results from growing social media profiles. We've already got the data for the number of Facebook likes and Twitter followers by month, we need the traffic they've driven to map against it.

Need this per month from Jan-13 to Nov-15, and across the whole network.

- Sessions from Facebook 
- Pageviews from Facebook

- Sessions from Twitter
- Pageviews from Twitter

**Comment by currycoder** [comment]
@fayebutler Would you be able to work this out using the query builder?  Then perhaps make a little command line tool (like the preview script!) to marshall the data from the sites in `config.TABLES` and dump it out to a CSV file?  EG:

```
month, facebook_sessions, facebook_pageviews, twitter_sessions, twitter_pageviews
01-2013, 30, 100, 10, 400
02-2013, 50, 200, 100, 900
```

This isn't strictly a statsdash thing - but it sounds like some of the logic could eventually be folded in to a quarterly report.  So it's probably worth doing it here.

**Comment by fayebutler** [comment]
@MrJonty  should have this finished to send over to you this afternoon. One thing I've noticed, especially for usgamer and eg.se, some months are lacking the data. For usg it doesn't have data before Jun 2013 (I guess that was before it was launched?) and for eg.se it seems to be fairly random it wont have any of the data or only data for Twitter or something.. 
just wanted to let you know in case you want me to do anything different - or just make a note of it?

**Comment by MrJonty** [comment]
Okay - for the presentation we only need the per-month traffic for the
whole network (not broken down into individual sites) so that's not a
problem, it'll just mean the total is a little bit lower for those periods.
Presumably we didn't have much of a FB following for USG pre-launch anyway
so the correlation shouldn't be unduly troubled.

That make sense?

On 2 December 2015 at 12:20, Faye Butler <notifications@github.com> wrote:

> @MrJonty <https://github.com/MrJonty> should have this finished to send
> over to you this afternoon. One thing I've noticed, especially for usgamer
> and eg.se, some months are lacking the data. For usg it doesn't have data
> before Jun 2013 (I guess that was before it was launched?) and for eg.se
> it seems to be fairly random it wont have any of the data or only data for
> Twitter or something..
> just wanted to let you know in case you want me to do anything different -
> or just make a note of it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamernetwork/gastatsdash/issues/17#issuecomment-161275923>
> .
>



-- 
*Rezzed *| Gamer Network
*P* +44 7775 641 446 *E* jon.hicks@rezzed.com *T* @MrJonty *Skype* jon.hicks
www.rezzed.com

**Comment by fayebutler** [comment]
Yep thats good, just thought I'd let you know!
