### ISSUE TITLE
Checking for available data

### ISSUE THREAD

**Issue by fayebutler** [gamernetwork/gastatsdash#22]
Need to update how we check if the data for a site is available. 
Currently checks page views for each hour of the day, but if a low traffic site has zero page views in a particular hour, it doesn't return that hour and therefore checks as data not available.

**Comment by fayebutler** [comment]
In fact it does return zero - but this still should be looked at as clearly not full proof.

**Comment by fayebutler** [comment]
Current status : Sends out a report after 2 days if it hasn't already with a warning saying "we are missing some data for the following sites... " 

This is fine with smaller sites, but if we have missing data for the larger sites again, should we look into something else?

**Comment by currycoder** [comment]
Closing this for now since it hasn't been an issue recently.  We can re-open later if we need.
