### ISSUE TITLE
Twitter targeting tool

### ISSUE THREAD

**Issue by MrJonty** [gamernetwork/gastatsdash#31]
As discussed (admittedly a little while ago) with Mark, it would be useful to identify the people on Twitter who drive the most referral traffic, and the patterns in which they do so. This information would enable us to target - ideally automatically - the new articles that we post so that they achieve maximum reach.

The data of interest would be:
- Which followers RT/share most regularly
- Which followers engage (reply to or share) most regularly
- Which of the above drive significant interaction and/or further sharing - so, for instance, a Notch RT would be much more valuable than a random spambot or a person with only 25 followers. Ratio of following/followers and a flag for follower count greater than X thousand would be a starting point.
- What time they tend to be on Twitter/interacting with things on Twitter
- What they tend to RT/talk about, as ascertained by tracking hashtags, keywords and other accounts they interact with.

This data would enable us to identify who to target with specific content and when.

Ideally we'd be able to pull this data from people who follow our own brands, but also other specified accounts - so if somebody terribly useful tends to RT IGN's stories about Dark Souls lore, for instance, we could @ them when we post our Dark Souls lore feature because we know that they're interested (and because many of our brands are verified, they would be notified of our mention.)

**Comment by currycoder** [comment]
@MrJonty from your perspective, what is higher value out of this and the youtube dash?

**Comment by currycoder** [comment]
Moved ticket to gamer-network repo, so closing.
