### ISSUE TITLE
Filtering for likely bot scraping sites

### ISSUE THREAD

**Issue by lukeinage** [gamernetwork/gastatsdash#32]
These sites all exist to scrape RSS feeds from gaming websites, and reproduce the RSS feed of EG's video output. They refer a surprising amount of traffic which I presume is just robotic. (I can't remember the time period for the PV counts below, I think it's YTD.)

Gamergossip.net: 80,689 
gamerdevices.com - 37,262 
gamersfun.net - 23,399 
gamingstime.com - 28,218 
gamersweb.net - 29,029 
gamerfanatics.com - 20,346 
gamersnews.net - 18,104

If we can get them shut down or struck out of the Analytics reports that would be lovely. Assuming I'm not missing something and they are legitimate sites.

**Comment by currycoder** [comment]
Investigate what the google analytics options are for eliminating this
