### ISSUE TITLE
Monthly social referral report for the network

### ISSUE THREAD

**Issue by MrJonty** [gamernetwork/gastatsdash#37]
I need a monthly rollup report showing the total sessions and pageviews from the top social networks.

- Facebook
- Twitter
- Reddit
- Top three other referring social networks

For each network show the sessions and pageviews from each across the whole network and the MoM and YoY change.

Each report shows these figures for the last 12 months, if that's possible - is that OK when we can't guarantee the "top three referrers" won't be the same each month?

Report goes to me.

**Comment by fayebutler** [comment]
How would it be best organised ?
e.g. by month

**Jan 2016** 
<table>
<thead>
<tr>
<th>Social Network</th>
<th>Sessions</th>
<th>PVs</th>
<th>MoM</th>
<th>YoY</th>
</tr>
</thead>
<tbody>
<tr>
<td>Facebook</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
<tr>
<td>Twitter</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
</tbody>
</table>


**Feb 2016** 
<table>
<thead>
<tr>
<th>Social Network</th>
<th>Sessions</th>
<th>PVs</th>
<th>MoM</th>
<th>YoY</th>
</tr>
</thead>
<tbody>
<tr>
<td>Facebook</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
<tr>
<td>Twitter</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
</tbody>
</table>


or, by social network

**Facebook** 
<table>
<thead>
<tr>
<th>Month</th>
<th>Sessions</th>
<th>PVs</th>
<th>MoM</th>
<th>YoY</th>
</tr>
</thead>
<tbody>
<tr>
<td>Jan 2016</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
<tr>
<td>Feb 2016</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
</tbody>
</table>

**Twitter** 
<table>
<thead>
<tr>
<th>Month</th>
<th>Sessions</th>
<th>PVs</th>
<th>MoM</th>
<th>YoY</th>
</tr>
</thead>
<tbody>
<tr>
<td>Jan 2016</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
<tr>
<td>Feb 2016</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
<td>XX</td>
</tr>
</tbody>
</table>

**Comment by MrJonty** [comment]
I think by social network, please!
