### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by currycoder** [gamernetwork/gastatsdash#49]
We need to document statsdash using sphinx http://www.sphinx-doc.org/en/stable/index.html and get it on to our readthedocs account.

Docs should be RST format - check out the 'getting started' tutorial here: http://www.sphinx-doc.org/en/stable/tutorial.html.  They can be multiple pages/sections as appropriate - whatever reads best!

The docs should roughly look like this: https://gamer-network-mormont.readthedocs-hosted.com/en/latest/service.html

Things to document:
- [ ] What's the goal of this project?  What features does it provide and who is it aimed at?
- [ ] How does someone quickly get started (feel free to duplicate this from the readme)
- [ ] Detail where configs live, what's are the important options, etc.
- [ ] Go through the interface from a developer's perspective of adding a new report to the schedule - what options are available for specifying the sites a report runs on, the time it runs, override options, other schedule metadata.
- [ ] What types of report are available?  What info do they offer?  Classnames/paths etc.  Image snippets could be handy.
- [ ] Deeper dive in to how the code is structured.  How do the following components work/fit together, what are the key classes to look at?
  - scheduler
  - report classes
  - data source classes
  - templates
- [ ] How would you go about extending statsdash?  How to add a new report?  How to add a new data source (imagine a twitter API)?

**Comment by fayebutler** [comment]
@currycoder images would be helpful, but is there an issue with putting our data on the docs? Is there a way round this, like blurring the names or something?

**Comment by thomasjthomasj** [comment]
Just finished a read through of the current docs and I've got some observations/notes:

**Getting started**

 - Not a major thing but it tells you to set up a virtual environment, but never tells you to activate it. If someone isn't aware of virtual environments this could cause some confusion. Also, it would probably be good to switch `virtualenv env` to `virtualenv <path to env>` or something
- When referencing the example config files, it doesn't mention that they are in the `Statsdash` directory so someone might assume they are in the root
- Typo - `shceduler `

**Analytics services**

- A lot of the files mentioned have incorrect casing, e.g. `Aggregate_data.py` is actually `aggregate_data.py`

**Comment by thomasjthomasj** [comment]
Config documentation makes no reference to important settings like `KEY_FILE`

**Comment by currycoder** [comment]
Got this merged in as is for now.  Didn't want the docs branch to go stale - we can use it for pointers in the next iteration.
