### ISSUE TITLE
Incorrect network data in daily site reports

### ISSUE THREAD

**Issue by MrJonty** [gamernetwork/gastatsdash#61]

**Comment by currycoder** [comment]
e.g. "Usgamer.net daily statsdash for Sun 16 Oct 2016" shows 'Change vs month to date last year' under 'Network Month To Date' as alarmingly low.  This is not the case when looking at the whole network statsdash.

**Comment by currycoder** [comment]
I think we got to the bottom of this off-list, it's all cool.
