### ISSUE TITLE
Additions and deletions

### ISSUE THREAD

**Issue by craigymunro** [gamernetwork/gastatsdash#63]
The following amendments need to be made to our emails:

- Please remove Prima from the statsdash, and from the 12-month totals going forwards - we want to show the total relative performance of the existing sites, and not leave huge MoM and YoY gaps where Prima used to be.
- Please remove purexbox.com
- Please remove video-game-wallpapers.com
- Please add tr.vg247.com as a separate site (not sure if it's already in with vg247)
- Please add outsidextra.com 

From Zendesk: https://gntech.zendesk.com/inbox/conversations/671

**Comment by currycoder** [comment]
This is done
